services:
  - type: web
    name: nutritrack-webapp
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/nutritrack-webapp/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
